displays:
  - name: "eDP-1-1"
    workspaces: [1,2,3,4,5]
  - name: HDMI-1-1
    workspaces: [6,7,8,9,0]
    randr_extra_options: "--left-of eDP1"
#  - name: DP1
#    workspaces: [1,3,5,7,9]
#    randr_extra_options: "--left-of HDMI1"
